#!/usr/bin/python
import numpy as np
import os
import matplotlib.pyplot as plt

from FortranFile import FortranFile as ff

f = ff('c.np.dat')
f.seek(0,os.SEEK_END)
data = f.readBackReals()

data = np.reshape(data, [100,12,100], 'F')
plt.pcolormesh(data[:,6,:])
plt.show()
