#!/usr/bin/env python
import argparse
import HybridAnimator as ha
from HybridHelper import parser

args = parser.parse_args()

a = ha.HybridAnimator(args.prefix, args.variable.name, args.variable.coordinate, args.save)
a.animate()
