#!/usr/bin/env python
import HybridAnimator2
#import argparse
#import HybridAnimator as ha
#from HybridHelper import parse_cmd_line
#
#args = parse_cmd_line()
#
#a = ha.HybridAnimator(args.prefix, args.variable.name, args.variable.coordinate, args.save)
#a.animate()
