#!/usr/bin/python
import numpy as np
from HybridReader2 import HybridReader2 as hr
import matplotlib.pyplot as plt
import matplotlib.ticker as plticker
from matplotlib.colors import Normalize, LogNorm, SymLogNorm
import colormaps as cmaps
from sys import argv
from bisect import bisect

plt.register_cmap(name='viridis', cmap=cmaps.viridis)

# Get density data
den = hr(argv[1],'np')
#den.repair_and_reset()

if int(argv[-1]) == -1:
    ddata = den.get_last_timestep()[-1]
else:
    for n in range(int(argv[-1])-1):
        den.skip_next_timestep()
    ddata = den.get_next_timestep()[-1]

# Get grid spacing
qx = den.para['qx']
qy = den.para['qy']
qzrange = den.para['qzrange']

# Find the center index of the grid
cx = den.para['nx']/2
cy = den.para['ny']/2
cz = den.para['zrange']/2

# the offset of pluto from the center isn't always availible
try:
    po = den.para['pluto_offset']
except KeyError:
    print("Couldn't get pluto_offset. It has been assumed to be 30, but it probably isn't.")
    po = 30

# Set constatnt for Pluto radius 
Rp = 1187. # km

# Shift grid so that Pluto lies at (0,0,0) and convert from km to Rp
qx = (qx - qx[len(qx)/2 + po])/Rp
qy = (qy - qy[len(qy)/2])/Rp
qzrange = (qzrange - qzrange[len(qzrange)/2])/Rp

# Make X-Y plot
X,Y = np.meshgrid(qx,qy)
plt.pcolormesh(X,Y,ddata[:,:,cz].transpose(), cmap=cmaps.viridis, norm=SymLogNorm(1), vmax=1e16)
plt.colorbar()
plt.xlim(qx[0],qx[-1])
plt.ylim(qy[0],qy[-1])
plt.title('Density')
plt.xlabel('X ($R_p$)')
plt.ylabel('Y ($R_p$)')
plt.gca().set_aspect('equal') # equal aspect ratio
loc = plticker.MultipleLocator(base=20)
ax = plt.gca()
ax.yaxis.set_major_locator(loc)



# Make X-Z plot
plt.figure()
X,Z = np.meshgrid(qx,qzrange)

plt.pcolormesh(X,Z,ddata[:,cy,:].transpose(), cmap=cmaps.viridis, norm=SymLogNorm(1), vmax=1e16)
plt.colorbar()
plt.xlim(qx[0],qx[-1])
plt.ylim(qzrange[0],qzrange[-1])
plt.title('Density')
plt.xlabel('X ($R_p$)')
plt.ylabel('Z ($R_p$)')
plt.gca().set_aspect('equal') # equal aspect ratio
loc = plticker.MultipleLocator(base=20)
ax = plt.gca()
ax.yaxis.set_major_locator(loc)

# Make Y-Z plot
xind = bisect(qx,-50)

plt.figure()
Y,Z = np.meshgrid(qy,qzrange)

plt.pcolormesh(Y,Z,ddata[xind,:,:].transpose(), cmap=cmaps.viridis, norm=SymLogNorm(1))
plt.colorbar()
plt.xlim(qy[0],qy[-1])
plt.ylim(qzrange[0],qzrange[-1])
plt.title('Density')
plt.xlabel('Y ($R_p$)')
plt.ylabel('Z ($R_p$)')
plt.gca().set_aspect('equal') # equal aspect ratio
loc = plticker.MultipleLocator(base=20)
ax = plt.gca()
ax.yaxis.set_major_locator(loc)

plt.show()
