#!/usr/bin/python
import numpy as np
from HybridReader2 import HybridReader2 as hr
import matplotlib.pyplot as plt
import matplotlib.ticker as plticker
import colormaps as cmaps
from sys import argv
plt.register_cmap(name='viridis', cmap=cmaps.viridis)

den = hr(argv[1],'np')
ddata = den.get_last_timestep()[-1]

qx = den.para['qx']
qy = den.para['qy']
qzrange = den.para['qzrange']
try:
    po = den.para['pluto_offset']
except KeyError:
    print('Check pluto_offset. Assumed to be 30')
    po = 30

Rp = 1187 # km

qx = (qx - qx[len(qx)/2 + po])/Rp
qy = (qy - qy[len(qy)/2])/Rp

cz = den.para['zrange']/2

X,Y = np.meshgrid(qx,qy)

plt.pcolormesh(X,Y,ddata[:,:,cz].transpose(), cmap=cmaps.viridis, vmin=0, vmax=10*pow(10,13))
plt.colorbar()

plt.xlim(qx[0],qx[-1])
plt.ylim(qy[0],qy[-1])

plt.title('Density')
plt.xlabel('X ($R_p$)')
plt.ylabel('Y ($R_p$)')
loc = plticker.MultipleLocator(base=20)
ax = plt.gca()
#ax.xaxis.set_major_locator(loc)
ax.yaxis.set_major_locator(loc)

plt.show()
