#!/usr/bin/python
import numpy as np
from HybridReader2 import HybridReader2 as hr
import matplotlib.pyplot as plt
import matplotlib.ticker as plticker
from matplotlib.colors import Normalize, LogNorm
import streams2 as streams
import colormaps as cmaps
from sys import argv
plt.register_cmap(name='viridis', cmap=cmaps.viridis)


# Get density data
den = hr(argv[1],'np', double=False)
ddata = den.get_last_timestep()[-1]

# Get magnetic field data
b1 = hr(argv[1],'bt_3d')
#b1.repair_and_reset()
bdata = b1.get_last_timestep()[-1]
bdata[1:,:,:,0] = (bdata[1:,:,:,0] + bdata[:-1,:,:,0])/2
bdata[:,1:,:,1] = (bdata[:,1:,:,1] + bdata[:,:-1,:,1])/2
bdata[:,:,1:,2] = (bdata[:,:,1:,2] + bdata[:,:,:-1,2])/2
#b0 = hr(argv[1],'b0_3d')
#b0data = b0.get_last_timestep()[-1]

# Get grid spacing
qx = den.para['qx']
qy = den.para['qy']
qzrange = den.para['qzrange']

# Find the center index of the grid
cx = den.para['nx']/2
cy = den.para['ny']/2
cz = den.para['zrange']/2

# the offset of pluto from the center isn't always availible
try:
    po = den.para['pluto_offset']
except KeyError:
    print("Couldn't get pluto_offset. It has been assumed to be 30, but it probably isn't.")
    po = 30

# Set constant for Pluto radius 
Rp = 1187. # km

# Shift grid so that Pluto lies at (0,0,0) and convert from km to Rp
qx = (qx - qx[len(qx)/2 + po])/Rp
qy = (qy - qy[len(qy)/2])/Rp
qzrange = (qzrange - qzrange[len(qzrange)/2])/Rp



# Make X-Y plot
X,Y = np.meshgrid(qx,qy)
plt.pcolormesh(X,Y,ddata[:,:,cz].T, cmap=cmaps.viridis, norm=LogNorm())
plt.colorbar()

def top_bot():
    n = 1
    l = 2*len(qx)/n-10
    seed_points = np.empty((l,2))
    seed_points[:l/2,0] = qx[:-5:n]
    seed_points[:l/2,1] = qy[len(qy)/2+5]
    seed_points[l/2:,0] = qx[:-5:n]
    seed_points[l/2:,1] = qy[len(qy)/2-5]
    return seed_points

def circle(r, n):
    seed_points = np.empty((n,2))
    theta = 2*np.pi/n
    for i in range(n):
        seed_points[i,0] = r*np.cos(i*theta)
        seed_points[i,1] = r*np.sin(i*theta)

seed_points = top_bot() #circle(20.,5)

streams.streamplot(plt.gca(), qx, qy, bdata[:,:,cz,0].T, bdata[:,:,cz,1].T, color='black', density=100,
        start_points=seed_points)
#plt.quiver(qx, qy, bdata[:,:,cz,0].T, bdata[:,:,cz,1].T, color='blue')
plt.xlim(qx[0],qx[-1])
plt.ylim(qy[0],qy[-1])
plt.title('Density')
plt.xlabel('X ($R_p$)')
plt.ylabel('Y ($R_p$)')
plt.gca().set_aspect('equal') # equal aspect ratio
loc = plticker.MultipleLocator(base=20)
plt.gca().yaxis.set_major_locator(loc)

## Make X-Z plot
#plt.figure()
#X,Z = np.meshgrid(qx,qzrange)
#
#plt.pcolormesh(X,Z,ddata[:,cy,:].transpose(), cmap=cmaps.viridis, norm=LogNorm())
#plt.colorbar()
#streams.streamplot(plt.gca(), qx, qzrange, bdata[:,cy,:,0].transpose(), bdata[:,cy,:,2].transpose(), color='white', density=2)
#plt.xlim(qx[0],qx[-1])
#plt.ylim(qzrange[0],qzrange[-1])
#plt.title('Density')
#plt.xlabel('X ($R_p$)')
#plt.ylabel('Z ($R_p$)')
#plt.gca().set_aspect('equal') # equal aspect ratio
#loc = plticker.MultipleLocator(base=20)
#ax = plt.gca()
#ax.yaxis.set_major_locator(loc)
#

plt.show()
