#!/usr/bin/python
from HybridHelper import parser
from HybridReader2 import HybridReader2 as hr

args = parser.parse_args()

hybrid_object = hr(args.prefix, args.variable, mode='r+')
hybrid_object.repair_and_reset()
