#!/bin/bash

mkdir oldstyle
ln -s $(pwd)/grid/* $(pwd)/oldstyle/
ln -s $(pwd)/particle/* $(pwd)/oldstyle/
ln -s $(pwd)/para.dat $(pwd)/oldstyle/
ln -s $(pwd)/inputs.dat $(pwd)/oldstyle/
ln -s $(pwd)/c.coord.dat $(pwd)/oldstyle/
